name: create_backup
description: A command-line application to create backups.
version: 1.0.0

environment:
  sdk: ^3.2.3

dependencies:
  archive: ^3.4.10
  flutter_lints: ^3.0.2
  path: ^1.9.0
  yaml: ^3.1.2
